---
title: "Pilot Community Recruitment"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## What is the Pilot Program? 

R Story is currently seeking additional communities to serve as pilot communities. Pilot communities will take part in virtual meetings with the R Story team to talk about their economic development strategies as well as receive an analysis of the demographic and economic data for their county.

Ideal pilot communities would be those in rural areas with fewer than 50,000 residents who have community economic development goals and can be at any stage of implementation.

The process will begin with a discussion of the community's goals and challenges in terms of economic development. R Story will perform a deep dive into the federal public data for each community, share the results of the data exploration, and seek feedback as to how the participant might use the data in their economic development work. Additionally, community members will receive access to the R Story prototype for use and feedback in their economic development work.

As a first pilot community, R Story worked with Manistee, Michigan who continues to use R Story in their economic development work. Marc Miller (Economic Development Director of Manistee, Michigan) states that “this tool was created to allow leaders in economic development to save time and easily access the data we need to champion our communities”.

###Sign Up to be a Pilot Community 

If you’re interested in participating as a pilot community for R Story, please fill out the form at this [link](<https://forms.gle/rNqLiPVp4szFWPzv8>).

For any questions or enquiries about partnership, please contact sing [mailto](mailto:rstorytool@gmail.com)